// Mocks generated by Mockito 5.4.6 from annotations
// in doctor_care/test/hba1c_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:doctor_care/domain/entities/hba1c.dart' as _i4;
import 'package:doctor_care/domain/repositories/hba1c_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Hba1cRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHba1cRepository extends _i1.Mock implements _i2.Hba1cRepository {
  MockHba1cRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addHba1cRecord(_i4.HbA1c? hba1c) =>
      (super.noSuchMethod(
            Invocation.method(#addHba1cRecord, [hba1c]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateHba1cRecord(_i4.HbA1c? hba1c) =>
      (super.noSuchMethod(
            Invocation.method(#updateHba1cRecord, [hba1c]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.HbA1c>> getHba1cRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getHba1cRecords, []),
            returnValue: _i3.Future<List<_i4.HbA1c>>.value(<_i4.HbA1c>[]),
          )
          as _i3.Future<List<_i4.HbA1c>>);

  @override
  _i3.Future<void> deleteHba1c(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHba1c, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
