import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('vi'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<String> supportedLanguageCodes = ['vi', 'en'];
  static const List<Locale> supportedLocales = [Locale('vi'), Locale('en')];

  String get languageCode => locale.languageCode.toLowerCase();

  // ══════════════════════════════════════
  // All translations
  // ══════════════════════════════════════
  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      // ── Navigation ──
      'home': 'Trang chủ',
      'nutrition': 'Dinh dưỡng',
      'health': 'Sức khoẻ',
      'profile': 'Cá nhân',

      // ── Profile Page ──
      'settings': 'Cài đặt',
      'personal_info': 'Thông tin cá nhân',
      'personal_info_sub': 'Cập nhật hồ sơ của bạn',
      'family_members': 'Thành viên gia đình',
      'family_members_sub': 'Quản lý hồ sơ gia đình',
      'account_security': 'Tài khoản & Bảo mật',
      'account_security_sub': 'Mật khẩu, xác thực',
      'preferences': 'Tùy chọn',
      'notifications': 'Thông báo',
      'notifications_sub': 'Quản lý nhắc nhở',
      'dark_mode': 'Chế độ tối',
      'dark_mode_on': 'Đang bật',
      'dark_mode_off': 'Đang tắt',
      'language': 'Ngôn ngữ',
      'language_vi': 'Tiếng Việt',
      'language_en': 'English',
      'support': 'Hỗ trợ',
      'help_faq': 'Trợ giúp & FAQ',
      'about_app': 'Về ứng dụng',
      'version': 'Phiên bản',
      'logout': 'Đăng xuất',
      'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất khỏi ứng dụng?',
      'cancel': 'Hủy',
      'user': 'Người dùng',
      'choose_language': 'Chọn ngôn ngữ',

      // ── Quick Stats ──
      'health_status': 'Sức khoẻ',
      'good': 'Tốt',
      'meals': 'Bữa ăn',
      'today': 'Hôm nay',
      'steps': 'Bước chân',
      'tracking': 'Đang theo dõi',
      'hello': 'Xin chào',
      'health_status_title': 'Tình trạng sức khỏe',
      'health_metrics_title': 'Chỉ số sức khỏe',
      'unit_mmhg': 'mmHg',
      'unit_percent': '%',
      'today_steps': 'Bước chân hôm nay',
      'unit_kcal': 'kcal',
      'unit_km': 'km',
      'step_activity_distribution': 'Phân bố mức vận động',
      'distance': 'Quãng đường',
      'step_status_sedentary': 'Ít vận động',
      'step_status_light': 'Vận động nhẹ',
      'step_status_moderate': 'Vận động vừa',
      'step_status_good': 'Tốt',
      'step_status_very_active': 'Rất tích cực',
      'details': 'Chi tiết',
      'Not verified': 'Chưa xác minh',

      // ── Photo Options ──
      'choose_from_gallery': 'Chọn từ thư viện',
      'take_photo': 'Chụp ảnh mới',
      'delete_avatar': 'Xóa ảnh đại diện',
      'uploading_photo': 'Đang tải ảnh lên...',
      'update_avatar_success': 'Cập nhật ảnh đại diện thành công!',
      'upload_failed': 'Không thể tải ảnh lên. Vui lòng thử lại!',
      'confirm': 'Xác nhận',
      'confirm_delete_avatar': 'Bạn có chắc chắn muốn xóa ảnh đại diện?',
      'delete': 'Xóa',
      'deleted_avatar': 'Đã xóa ảnh đại diện',
      'error': 'Lỗi',

      // ── Today Target ──
      'today_target': 'Mục tiêu hôm nay',
      'drink_water': 'Uống nước',
      'step_count': 'Bước chân',
      'meal_calories': 'Bữa ăn',
      'step_goal': '10000 bước',
      'water_goal': '2000 ml',
      'calorie_goal': '2000 kcal',

      // ── Health Page ──
      'health_tracking': 'Theo dõi sức khoẻ tổng quát',
      'health_metrics': 'Các chỉ số sức khoẻ',
      'health_advice': 'Lời khuyên sức khoẻ',

      // ── Nutrition Page ──
      'nutrition_distribution': 'Phân bổ dinh dưỡng',
      'today_meals': 'Bữa ăn hôm nay',
      'no_meals_today': 'Chưa có bữa ăn nào',
      'no_meals_today_full': 'Chưa có bữa ăn nào hôm nay',
      'add_meal_hint': 'Thêm bữa ăn để theo dõi dinh dưỡng',
      'nutrition_summary': 'Tổng kết dinh dưỡng',
      'add_new_dish': 'Thêm mới',
      'meal_suggestion_ai_title': 'AI Gợi ý bữa ăn',
      'meal_suggestion_ai_subtitle': 'Dựa trên chỉ số sức khỏe của bạn',
      'meal_suggestion_smart_title': 'Gợi ý bữa ăn thông minh',
      'meal_suggestion_smart_desc':
          'AI sẽ phân tích chỉ số sức khỏe, dinh dưỡng đã nạp\nvà đề xuất bữa ăn phù hợp nhất cho bạn',
      'meal_suggestion_choose_type': 'Chọn loại bữa ăn',
      'meal_suggestion_next_meal': 'Bữa ăn tiếp theo',
      'meal_suggestion_breakfast': 'Bữa sáng',
      'meal_suggestion_lunch': 'Bữa trưa',
      'meal_suggestion_dinner': 'Bữa tối',
      'meal_suggestion_snack': 'Bữa phụ',
      'meal_suggestion_feature_health_metrics':
          'Phân tích chỉ số sức khỏe gần đây nhất',
      'meal_suggestion_feature_macro_gaps':
          'Tính calo/macro còn thiếu trong ngày',
      'meal_suggestion_feature_tdee': 'Tính TDEE dựa trên BMI và bước chân',
      'meal_suggestion_feature_vietnamese_food': 'Gợi ý món Việt Nam phù hợp',
      'meal_suggestion_generate_now': 'AI Gợi ý ngay',
      'meal_suggestion_loading_title': 'AI đang phân tích sức khỏe...',
      'meal_suggestion_loading_desc': 'Đang đọc chỉ số sức khỏe gần đây nhất',
      'meal_suggestion_error_title': 'Không thể tạo gợi ý',
      'meal_suggestion_daily_summary': 'Tóm tắt sức khỏe hôm nay',
      'meal_suggestion_nutrition_gaps': 'Chất dinh dưỡng cần bổ sung',
      'meal_suggestion_suggested_dishes': 'Món ăn gợi ý',
      'meal_suggestion_regenerate': 'Gợi ý lại',
      'capture_meal_to_analyze': 'Chụp ảnh món ăn để phân tích dinh dưỡng',
      'food_count': '{count} món',
      'today_calories': 'Calories hôm nay',
      'weekday_mon': 'Thứ Hai',
      'weekday_tue': 'Thứ Ba',
      'weekday_wed': 'Thứ Tư',
      'weekday_thu': 'Thứ Năm',
      'weekday_fri': 'Thứ Sáu',
      'weekday_sat': 'Thứ Bảy',
      'weekday_sun': 'Chủ nhật',

      // ── Meal Capture ──
      'ai_analyzing': 'AI đang nhận diện thành phần dinh dưỡng',
      'nutrition_analysis_ai': 'Phân tích dinh dưỡng\nbằng AI',
      'capture_hint':
          'Chụp ảnh hoặc chọn ảnh bữa ăn, AI sẽ nhận diện\nvà phân tích thông tin dinh dưỡng chi tiết.',
      'fast_recognition': 'Nhận diện nhanh',
      'detailed_calories': 'Chi tiết calo',
      'food_database': '852+ thực phẩm',
      'take_photo_btn': 'Chụp ảnh bữa ăn',
      'choose_from_gallery_btn': 'Chọn từ thư viện',

      // ── Meal Detail ──
      'food_items': 'Thành phần thực phẩm',
      'health_recommendations': 'Lời khuyên sức khoẻ',
      'notes': 'Ghi chú',
      'delete_meal': 'Xóa bữa ăn',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'fiber': 'Chất xơ',
      'calories': 'Calo',
      'glycemic_index': 'Chỉ số GI',

      // ── Meal Analysis ──
      'meal_analysis_result_title': 'Kết quả phân tích',
      'meal_analysis_need_food_item_to_save': 'Cần có ít nhất 1 món ăn để lưu!',
      'meal_analysis_save_error': 'Lỗi khi lưu: {error}',
      'meal_analysis_saved_success': 'Đã lưu bữa ăn thành công!',
      'meal_capture_title': 'Phân tích bữa ăn',
      'analyzing_meal': 'Đang phân tích bữa ăn...',
      'meal_type_label': 'Loại bữa',
      'dish_name_label': 'Tên món ăn',
      'dish_name_hint': 'Nhập tên món ăn',
      'overview': 'Tổng quan',
      'total_calories': 'Tổng calo',
      'tap_to_edit': 'Chạm để chỉnh sửa',
      'save_meal': 'Lưu bữa ăn',
      'edit_food_item': 'Chỉnh sửa: {name}',
      'portion_grams_label': 'Khối lượng (gram)',
      'nutrition_recalc_note': 'Giá trị dinh dưỡng sẽ được tính lại theo tỷ lệ',
      'invalid_image_title': 'Ảnh không hợp lệ',
      'invalid_image_hint': 'Vui lòng chụp hoặc chọn ảnh rõ ràng của món ăn để AI có thể phân tích chính xác.',
      'invalid_image_retake': 'Chụp ảnh lại',
      'invalid_image_pick_gallery': 'Chọn ảnh khác',

      // ── Auth ──
      'forgot_password_title': 'Quên mật khẩu',
      'reset_password_title': 'Đặt lại mật khẩu',
      'reset_password_desc':
          'Nhập email của bạn để nhận liên kết đặt lại mật khẩu. Chúng tôi sẽ gửi hướng dẫn đến địa chỉ email này.',
      'email': 'Email',
      'your_email_hint': 'Email của bạn',
      'please_enter_email': 'Vui lòng nhập email',
      'invalid_email_format': 'Email không đúng định dạng',
      'send_reset_link': 'Gửi liên kết đặt lại',
      'back_to_login': 'Quay lại đăng nhập',
      'reset_email_sent':
          'Email khôi phục mật khẩu đã được gửi! Vui lòng kiểm tra hộp thư.',
      'note': 'Lưu ý:',
      'reset_password_note_bullets':
          '• Kiểm tra cả hộp thư spam/junk\n• Liên kết có hiệu lực trong 1 giờ\n• Nếu không nhận được email, thử lại sau 5 phút',

      // ── Account & Security ──
      'reset_password': 'Đặt lại mật khẩu',
      'send_reset_password_email': 'Gửi email đặt lại mật khẩu',
      'reload_account_status': 'Tải lại trạng thái tài khoản',
      'refresh_verification_state': 'Làm mới trạng thái xác minh',
      'sign_out_and_clear_session': 'Đăng xuất và xóa phiên đã lưu',
      'verified': 'Đã xác minh',
      'not_verified': 'Chưa xác minh',

      // ── Common ──
      'save': 'Lưu',
      'edit': 'Sửa',
      'reset': 'Đặt lại',
      'search': 'Tìm kiếm',
      'loading': 'Đang tải...',
      'no_data': 'Không có dữ liệu',
      'error_with_message': 'Lỗi: {message}',

      'time': 'Thời gian',
      'status': 'Trạng thái',
      'classification': 'Phân loại',
      'clear_filter': 'Xóa bộ lọc',
      'record_count': '{count} bản ghi',
      'total_records': 'Tổng bản ghi',
      'average': 'Trung bình',
      'steps_per_day': '{count} bước/ngày',
      'retry': 'Thử lại',
      'add': 'Thêm',
      'close': 'Đóng',
      'not_selected': 'Chưa chọn',
      'not_available': 'N/A',
      'no_results_found': 'Không tìm thấy kết quả',
      'try_change_filters': 'Thử thay đổi bộ lọc của bạn',
      'no_data_for_filter': 'Không có dữ liệu cho bộ lọc này',
      'no_data_matching_filter': 'Không có dữ liệu phù hợp với bộ lọc',
      'activity_level': 'Mức vận động',
      'activity_low': 'Ít vận động',
      'activity_moderate': 'Vừa phải',
      'activity_active': 'Năng động',
      'bmi_underweight': 'Thiếu cân',
      'bmi_overweight': 'Thừa cân',
      'bmi_obese': 'Béo phì',
      'blood_sugar_status': 'Trạng thái đường huyết',
      'blood_sugar_low': 'Hạ đường huyết',
      'blood_sugar_prediabetes_short': 'Tiền ĐTĐ',
      'blood_sugar_prediabetes': 'Tiền đái tháo đường',
      'blood_sugar_diabetes': 'Đái tháo đường',
      'measurement_time': 'Thời điểm đo',
      'before_sleep': 'Trước ngủ',
      'after_wake': 'Sau ngủ dậy',
      'sleep_duration': 'Thời lượng ngủ',
      'sleep_quality': 'Chất lượng',
      'sleep_duration_severe_shortage': 'Thiếu ngủ N.trọng',
      'sleep_duration_severe_shortage_full': 'Thiếu ngủ nghiêm trọng',
      'sleep_duration_shortage': 'Thiếu ngủ',
      'sleep_duration_ok': 'Tạm đủ',
      'sleep_duration_good': 'Tốt',
      'filter_results': 'Lọc kết quả',
      'filter': 'Bộ lọc',
      'all': 'Tất cả',
      'manual_entry': 'Nhập tay',
      'device': 'Thiết bị',
      'status_normal': 'Bình thường',
      'status_caution': 'Chú ý',
      'status_no_data': 'Chưa có',
      'health_status_low': 'Thấp',
      'health_status_high': 'Cao',
      'health_status_slightly_low': 'Thấp nhẹ',
      'health_status_slightly_high': 'Cao nhẹ',
      'status_monitoring': 'Theo dõi',
      'status_attention': 'Cần chú ý',
      'status_danger': 'Nguy hiểm',
      'apply': 'Áp dụng',
      'date_range_invalid': 'Ngày bắt đầu phải trước ngày kết thúc',
      'temp_low': 'Hạ nhiệt',
      'temp_mild_fever': 'Sốt nhẹ',
      'temp_moderate_fever': 'Sốt vừa',
      'temp_high_fever': 'Sốt cao',
      'track_temperature': 'Theo dõi nhiệt độ',
      'add_temperature_title': 'Thêm chỉ số nhiệt độ',
      'edit_temperature_title': 'Cập nhật chỉ số nhiệt độ',
      'confirm_delete_temperature':
          'Bạn có chắc chắn muốn xoá chỉ số nhiệt độ này không?',
      'no_temperature_records': 'Chưa có dữ liệu nhiệt độ',
      'temperature_value': 'Nhiệt độ',
      'enter_temperature': 'Nhập chỉ số nhiệt độ',
      'no_step_data': 'Không có dữ liệu bước chân',
      'no_sleep_data': 'Không có dữ liệu giấc ngủ',
      'no_blood_sugar_data': 'Không có dữ liệu đường huyết',
      'no_cholesterol_data': 'Không có dữ liệu cholesterol',
      'no_blood_pressure_data': 'Không có dữ liệu huyết áp',
      'no_hba1c_data': 'Không có dữ liệu HbA1c',
      'steps_unit': 'bước',
      'meal_status_fasting': 'Lúc đói',
      'meal_status_before_meal': 'Trước ăn',
      'meal_status_after_meal': 'Sau ăn 2h',
      'meal_status_random': 'Ngẫu nhiên',

      // ── Notifications ──
      'notifications_title': 'Thông báo',
      'unread_count': '{count} chưa đọc',
      'mark_all': 'Đánh dấu tất cả',
      'deleted_notification': 'Đã xóa thông báo',
      'filter_unread': 'Chưa đọc',
      'filter_read': 'Đã đọc',
      'no_unread_notifications': 'Không có thông báo chưa đọc',

      // ── Meal history ──
      'meal_history_title': 'Lịch sử bữa ăn',
      'ai_analyze': 'AI phân tích',
      'no_meals_in_range': 'Không có bữa ăn nào trong khoảng thời gian này',
      'try_another_range': 'Thử chọn khoảng thời gian khác',
      'tap_ai_to_start': 'Nhấn nút "AI phân tích" để bắt đầu',
      'week': 'Tuần',
      'month': 'Tháng',

      // ── Insert dish (manual meal) ──
      'add_new_meal_title': 'Thêm mới món ăn',
      'dish_name_section': 'Tên món ăn',
      'dish_name_example_hint': 'VD: Phở Bò, Cơm Tấm...',
      'search_food_hint': 'Tìm kiếm thực phẩm...',
      'meal_notes_hint_optional': 'Ghi chú về bữa ăn (tùy chọn)...',
      'per_100g': 'Trên 100g',
      'please_add_at_least_one_food': 'Vui lòng thêm ít nhất 1 thực phẩm',
      'default_meal_name': 'Bữa ăn',

      // ── Health Goals ──
      'health_goal_title': 'Mục tiêu sức khỏe',
      'health_goal_daily_activity': 'Hoạt động hàng ngày',
      'health_goal_steps_title': 'Số bước chân',
      'health_goal_steps_subtitle': 'Mục tiêu bước chân mỗi ngày',
      'health_goal_steps_edit_title': 'Mục tiêu bước chân',
      'health_goal_water_title': 'Lượng nước uống',
      'health_goal_water_subtitle': 'Mục tiêu uống nước mỗi ngày',
      'health_goal_water_edit_title': 'Mục tiêu uống nước',
      'health_goal_calories_title': 'Lượng calo nạp vào',
      'health_goal_calories_subtitle': 'Mục tiêu calo mỗi ngày',
      'health_goal_calories_edit_title': 'Mục tiêu calo',
      'health_goal_sleep_weight': 'Giấc ngủ & Cân nặng',
      'health_goal_sleep_title': 'Thời gian ngủ',
      'health_goal_sleep_subtitle': 'Mục tiêu số giờ ngủ mỗi đêm',
      'health_goal_sleep_edit_title': 'Mục tiêu giấc ngủ',
      'health_goal_weight_title': 'Cân nặng mục tiêu',
      'health_goal_weight_subtitle': 'Mục tiêu cân nặng của bạn',
      'health_goal_not_set': 'Chưa đặt mục tiêu',
      'health_goal_reset_defaults': 'Đặt lại về mặc định',
      'health_goal_enter_value': 'Nhập giá trị ({min} – {max} {unit})',
      'health_goal_invalid_value': 'Giá trị không hợp lệ',
      'health_goal_value_range': 'Phải từ {min} đến {max}',
      'health_goal_reset_title': 'Đặt lại mục tiêu',
      'health_goal_reset_confirm':
          'Tất cả mục tiêu sẽ được đặt lại về giá trị mặc định. Bạn có chắc không?',

      // ── Health Overview ──
      'health_overview_title': 'Sức khoẻ tổng quan',
      'health_overview_measurements': 'Đo lường',
      'health_overview_warnings': 'Cảnh báo',
      'health_overview_this_year': 'Năm nay',
      'health_overview_detailed_stats': 'Thống kê chi tiết',
      'health_overview_total_measurements': 'Tổng số đo lường',
      'health_overview_daily_average': 'Trung bình mỗi ngày',
      'health_overview_abnormal_data': 'Dữ liệu bất thường',
      'health_overview_times_count': '{count} lần',
      'health_overview_bp_warning_title': 'Chú ý Huyết áp',
      'health_overview_bp_warning_desc':
          'Huyết áp có dấu hiệu cao. Hạn chế ăn mặn, tập thể dục nhẹ nhàng.',
      'health_overview_bp_stable_title': 'Huyết áp ổn định',
      'health_overview_bp_stable_desc':
          'Tiếp tục duy trì chế độ ăn uống lành mạnh và tập thể dục đều đặn.',
      'health_overview_glucose_control_title': 'Kiểm soát đường huyết',
      'health_overview_glucose_control_desc':
          'Chỉ số đường huyết cao. Tham khảo ý kiến bác sĩ và kiểm soát chế độ ăn.',
      'health_overview_glucose_stable_title': 'Đường huyết ổn định',
      'health_overview_glucose_stable_desc':
          'Hãy duy trì đo kiểm tra HbA1c định kỳ để theo dõi.',
      'health_overview_fever_title': 'Có thể bạn đang sốt',
      'health_overview_fever_desc':
          'Nhiệt độ cơ thể cao, hãy uống nhiều nước và theo dõi sát sao.',
      'health_overview_temperature_normal_title': 'Giữ ấm cơ thể',
      'health_overview_temperature_normal_desc':
          'Nhiệt độ cơ thể bình thường. Duy trì nhiệt độ môi trường phù hợp.',

      // ── Health Page & Widgets ──
      'tracking_target': 'Đối tượng theo dõi',
      'today_overview': 'Tổng quan hôm nay',
      'blood_pressure': 'Huyết áp',
      'hba1c_index': 'Chỉ số HbA1c',
      'temperature': 'Nhiệt độ',
      'spo2_heart_rate': 'SPO2 & Nhịp tim',
      'bmi_weight': 'BMI & Cân nặng',
      'water_intake': 'Lượng nước',
      'blood_sugar': 'Đường huyết',
      'sleep': 'Giấc ngủ',
      'cholesterol_label': 'Cholesterol',
      'daily_water': 'Nước uống',
      'heart_rate_label': 'Nhịp tim',
      'unit_ml': 'ml',
      'unit_hour': 'giờ',
      'unit_bpm': 'bpm',
      'add_spo2_heart_rate_title': 'Thêm SPO2 & Nhịp tim',
      'edit_spo2_heart_rate_title': 'Cập nhật SPO2 & Nhịp tim',
      'confirm_delete_spo2_heart_rate':
          'Bạn có chắc chắn muốn xoá bản ghi này không?',
      'no_spo2_heart_rate_records': 'Chưa có dữ liệu SPO2 & Nhịp tim',
      'spo2_empty_hint': 'Nhấn nút + để nhập tay hoặc đồng bộ từ thiết bị',
      'enter_spo2': 'Nhập SPO2 (70-100%)',
      'enter_heart_rate': 'Nhập nhịp tim (30-200 bpm)',
      'sync': 'Đồng bộ',
      'sync_from_health_connect': 'Đồng bộ từ Health Connect',
      'health_connect_sync_title': 'Đồng bộ Health Connect',
      'health_connect_sync_desc':
          'Lấy dữ liệu SpO2 & Nhịp tim từ thiết bị đeo qua Health Connect',
      'syncing_health_connect': 'Đang đồng bộ từ Health Connect...',
      'please_wait_moment': 'Vui lòng chờ trong giây lát',
      'sync_spo2_banner_desc': 'Đồng bộ SpO2 & nhịp tim từ thiết bị đeo',
      'sync_success_count': 'Đã đồng bộ {count} bản ghi từ Health Connect',
      'last_7_days': '7 ngày qua',
      'last_30_days': '30 ngày qua',
      'spo2_status_mild': 'Thiếu oxy nhẹ',
      'spo2_status_moderate': 'Thiếu oxy vừa',
      'spo2_status_severe': 'Thiếu oxy nghiêm trọng',
      'heart_rate_slow': 'Nhịp chậm',
      'heart_rate_fast_mild': 'Nhịp nhanh nhẹ',
      'heart_rate_fast_moderate': 'Nhịp nhanh vừa',
      'heart_rate_fast_high': 'Nhịp nhanh cao',
      'error_occurred': 'Đã xảy ra lỗi',
      'tip_today': '💡 Lời khuyên hôm nay',
      'tip_water_title': 'Uống đủ nước',
      'tip_water_desc':
          'Hãy uống ít nhất 2 lít nước mỗi ngày để duy trì sức khoẻ và giúp cơ thể vận hành tốt nhất.',
      'tip_walk_title': 'Đi bộ mỗi ngày',
      'tip_walk_desc':
          'Đi bộ 30 phút mỗi ngày giúp giảm nguy cơ bệnh tim mạch và cải thiện tâm trạng.',
      'tip_sleep_title': 'Ngủ đủ giấc',
      'tip_sleep_desc':
          'Ngủ 7-8 tiếng mỗi đêm giúp cơ thể phục hồi và tăng cường hệ miễn dịch.',
      'tip_eat_title': 'Ăn uống lành mạnh',
      'tip_eat_desc':
          'Bổ sung rau xanh và trái cây vào bữa ăn hàng ngày để cung cấp vitamin thiết yếu.',
      'tip_relax_title': 'Thư giãn tinh thần',
      'tip_relax_desc':
          'Dành 10 phút mỗi ngày để thiền hoặc hít thở sâu giúp giảm stress hiệu quả.',
      'tip_bp_title': 'Theo dõi huyết áp',
      'tip_bp_desc':
          'Đo huyết áp định kỳ để phát hiện sớm các vấn đề tim mạch và điều chỉnh lối sống.',
      'tip_exercise_title': 'Tập thể dục',
      'tip_exercise_desc':
          'Tập thể dục ít nhất 150 phút/tuần để tăng cường sức khoẻ tim mạch và xương khớp.',
      'weekly_activity': 'Hoạt động tuần này',
      'active_days_recorded': '{days}/7 ngày có ghi nhận dữ liệu',
      'no_data_this_week': 'Chưa có dữ liệu tuần này',
      'this_week': 'Tuần này',
      'target_reached': 'Đạt mục tiêu',
      'target': 'Mục tiêu',
      'day_mon': 'T2',
      'day_tue': 'T3',
      'day_wed': 'T4',
      'day_thu': 'T5',
      'day_fri': 'T6',
      'day_sat': 'T7',
      'day_sun': 'CN',

      // ── Auth - Login ──
      'login_title': 'Đăng nhập',
      'login_welcome_back': 'Chào mừng bạn trở lại!',
      'login_subtitle': 'Quản lý sức khoẻ của bạn',
      'password': 'Mật khẩu',
      'remember_me': 'Ghi nhớ',
      'forgot_password': 'Quên mật khẩu?',
      'login_btn': 'Đăng nhập',
      'login_with_google': 'Đăng nhập với Google',
      'or': 'Hoặc',
      'no_account': 'Chưa có tài khoản? ',
      'login_failed': 'Đăng nhập thất bại',
      // ── Auth - Register ──
      'register': 'Đăng ký',
      'register_title': 'Tạo Tài Khoản',
      'register_subtitle': 'Đăng ký để bắt đầu quản lý sức khỏe',
      'confirm_password': 'Xác nhận mật khẩu',
      'password_requirements': 'Yêu cầu mật khẩu:',
      'req_valid_email': 'Email đúng định dạng (abc@email.com)',
      'req_password_min': 'Mật khẩu ít nhất 6 ký tự',
      'req_password_match': 'Mật khẩu xác nhận khớp',
      'agree_to': 'Tôi đồng ý với ',
      'terms_of_use': 'Điều khoản sử dụng',
      'and': 'và',
      'privacy_policy': 'Chính sách bảo mật',
      'register_btn': 'Đăng ký',
      'register_failed': 'Đăng ký thất bại',
      'have_account': 'Đã có tài khoản? ',
      'please_enter_password': 'Vui lòng nhập mật khẩu',
      'password_min_6': 'Mật khẩu phải có ít nhất 6 ký tự',
      'please_enter_confirm_password': 'Vui lòng nhập lại mật khẩu',
      'password_not_match': 'Mật khẩu không khớp',

      // ── Family Profile ──
      'manage_family_profiles': 'Quản lý hồ sơ gia đình',
      'add_profile': 'Thêm hồ sơ',
      'no_family_profiles': 'Chưa có hồ sơ gia đình',
      'family_profile_empty_hint':
          'Thêm hồ sơ người thân để theo dõi sức khỏe cho cả gia đình',
      'selected': 'Đã chọn',
      'years_old': 'tuổi',
      'years_old_count': '{count} tuổi',
      'add_new_profile_title': 'Thêm mới hồ sơ',
      'update_profile_title': 'Cập nhật hồ sơ',
      'basic_info': 'Thông tin cơ bản',
      'health_info': 'Thông tin sức khỏe',
      'full_name': 'Họ và tên',
      'please_enter_full_name': 'Vui lòng nhập họ tên',
      'relationship_label': 'Mối quan hệ *',
      'gender': 'Giới tính',
      'gender_male': 'Nam',
      'gender_female': 'Nữ',
      'gender_other': 'Khác',
      'blood_type': 'Nhóm máu',
      'height_cm': 'Chiều cao (cm)',
      'weight_kg': 'Cân nặng (kg)',
      'height_invalid': 'Chiều cao không hợp lệ',
      'weight_invalid': 'Cân nặng không hợp lệ',
      'enter_name_preview': 'Nhập tên để xem trước',
      'confirm_delete_profile': 'Bạn có chắc chắn muốn xoá hồ sơ này không?',
      'rel_self': 'Bản thân',
      'rel_spouse': 'Vợ/Chồng',
      'rel_child': 'Con',
      'rel_parent': 'Bố/Mẹ',
      'rel_sibling': 'Anh/Chị/Em',
      'rel_grandparent': 'Ông/Bà',
      'rel_other': 'Khác',
      'update_btn': 'Cập nhật',

      // ── Edit Profile ──
      'edit_profile_title': 'Chỉnh sửa hồ sơ',
      'phone_number': 'Số điện thoại',
      'date_of_birth_label': 'Ngày sinh',
      'choose_date_of_birth': 'Chọn ngày sinh',
      'address': 'Địa chỉ',
      'emergency_contact': 'Liên hệ khẩn cấp',
      'emergency_contact_name': 'Tên người liên hệ',
      'emergency_phone': 'Số điện thoại khẩn cấp',
      'update_success': '✅ Cập nhật thành công!',
      'not_updated': 'Chưa cập nhật',

      // ── Blood Sugar / Insert ──
      'track_blood_sugar': 'Theo dõi đường huyết',
      'add_blood_sugar_title': 'Thêm mới đường huyết',
      'edit_blood_sugar_title': 'Chỉnh sửa đường huyết',
      'confirm_delete_blood_sugar':
          'Bạn có chắc chắn muốn xoá chỉ số đường huyết này không?',
      'no_blood_sugar_records': 'Chưa có dữ liệu đường huyết',
      'add_new_record_hint': 'Nhấn nút + để thêm bản ghi mới',
      'select_time': 'Chọn thời gian',
      'blood_sugar_value': 'Đường huyết (mg/dL)',
      'enter_blood_sugar': 'Nhập chỉ số đường huyết',
      'note_optional': 'Ghi chú (tuỳ chọn)',
      'note_hint': 'Nhập ghi chú...',

      // ── Blood Pressure ──
      'track_blood_pressure': 'Theo dõi huyết áp',
      'add_blood_pressure_title': 'Thêm mới chỉ số huyết áp',
      'edit_blood_pressure_title': 'Chỉnh sửa chỉ số huyết áp',
      'confirm_delete_blood_pressure':
          'Bạn có chắc chắn muốn xoá chỉ số huyết áp này không?',
      'blood_pressure_chart_title': 'Biểu đồ huyết áp',
      'blood_pressure_systolic': 'Huyết áp tâm thu',
      'blood_pressure_diastolic': 'Huyết áp tâm trương',
      'enter_blood_pressure_systolic': 'Nhập chỉ số tâm thu',
      'enter_blood_pressure_diastolic': 'Nhập chỉ số tâm trương',
      'blood_pressure_systolic_greater_error':
          'Chỉ số tâm thu phải lớn hơn tâm trương',
      'blood_pressure_diastolic_less_error':
          'Chỉ số tâm trương phải nhỏ hơn tâm thu',
      'blood_pressure_low': 'Huyết áp thấp',
      'blood_pressure_elevated': 'Bình thường cao',
      'blood_pressure_stage_1': 'Tăng huyết áp độ 1',
      'blood_pressure_stage_2': 'Tăng huyết áp độ 2',
      'blood_pressure_stage_3': 'Tăng huyết áp độ 3',
      'please_select_date_range': 'Vui lòng chọn khoảng thời gian',

      // ── HbA1c ──
      'track_hba1c': 'Theo dõi HbA1c',
      'hba1c_chart_title': 'Biểu đồ HbA1c',
      'add_hba1c_title': 'Thêm chỉ số HbA1c',
      'edit_hba1c_title': 'Cập nhật chỉ số HbA1c',
      'confirm_delete_hba1c':
          'Bạn có chắc chắn muốn xoá chỉ số HbA1c này không?',
      'no_hba1c_records': 'Chưa có dữ liệu HbA1c',
      'enter_hba1c': 'Nhập chỉ số HbA1c',
      'hba1c_status_normal': 'Bình thường',
      'hba1c_status_prediabetes': 'Tiền đái tháo đường',
      'hba1c_status_diabetes': 'Đái tháo đường',
      'hba1c_status_high': 'Cao',
      'hba1c_info_prefix': 'Chỉ số ',
      'hba1c_info_average': ' phản ánh mức đường huyết trung bình trong ',
      'hba1c_info_period': '2-3 tháng gần nhất. ',
      'hba1c_info_target':
          'Mục tiêu điều trị được khuyến cáo cho người mắc đái tháo đường là',
      'hba1c_target_value': 'HbA1c < 7%',

      // ── Medical Notes (Admin) ──
      'medical_notes_title': 'Ghi chú chuyên môn',
      'selected_patient': 'Bệnh nhân đã chọn',
      'select_patient': 'Chọn bệnh nhân',
      'tap_to_select_patient': 'Nhấn để chọn bệnh nhân',
      'choose_patient_title': 'Chọn Bệnh Nhân',
      'search_patient_hint': 'Tìm kiếm bệnh nhân...',
      'patient_not_found': 'Không tìm thấy bệnh nhân',
      'try_other_keyword': 'Thử tìm kiếm với từ khóa khác',
      'start_notes': 'Bắt đầu ghi chú',
      'tap_patient_bar': 'Nhấn vào thanh chọn bệnh nhân ở trên',
      'to_view_or_add': 'để xem hoặc thêm ghi chú chuyên môn',
      'note_list': 'Danh sách ghi chú',
      'add_note': 'Thêm ghi chú',
      'not_yet_updated': 'Chưa cập nhật',

      //notifications
      "no_read_notifications": "Không có thông báo đã đọc",
      "no_notifications": "Chưa có thông báo nào",
      "just_now": "Vừa xong",
      "minutes_ago": "{count} phút trước",
      "hours_ago": "{count} giờ trước",
      "days_ago": "{count} ngày trước",

      // ── Menstrual Cycle ──
      'menstrual_cycle': 'Chu kỳ kinh nguyệt',
      'menstrual_cycle_subtitle': 'ngày/chu kỳ',
      'menstrual_cycle_overview': 'Tổng quan',
      'menstrual_cycle_calendar': 'Lịch',
      'menstrual_cycle_history': 'Lịch sử',
      'menstrual_cycle_add': 'Thêm chu kỳ',
      'menstrual_cycle_edit': 'Chỉnh sửa chu kỳ',
      'menstrual_cycle_new': 'Thêm chu kỳ mới',
      'menstrual_cycle_start_date': 'Ngày bắt đầu hành kinh',
      'menstrual_cycle_end_date': 'Ngày kết thúc hành kinh (tuỳ chọn)',
      'menstrual_cycle_period_length': 'Thời gian hành kinh',
      'menstrual_cycle_symptoms': 'Triệu chứng',
      'menstrual_cycle_note': 'Ghi chú (tuỳ chọn)',
      'menstrual_cycle_save': 'Lưu chu kỳ',
      'menstrual_cycle_update': 'Cập nhật',
      'menstrual_cycle_delete_confirm':
          'Bạn có chắc chắn muốn xóa chu kỳ này không?',
      'menstrual_cycle_no_data': 'Chưa có dữ liệu chu kỳ',
      'menstrual_cycle_next': 'Kỳ kinh tiếp',
      'menstrual_cycle_ovulation': 'Rụng trứng',
      'menstrual_cycle_fertile_window': 'Cửa sổ thụ thai',
      'menstrual_cycle_ongoing': 'Đang diễn ra',
      'menstrual_cycle_latest': 'Chu kỳ gần nhất',
      'menstrual_cycle_avg_length': 'Chu kỳ TB',
      'menstrual_cycle_total': 'Tổng chu kỳ',
      'menstrual_cycle_phase_period': 'Đang hành kinh',
      'menstrual_cycle_phase_fertile': 'Cửa sổ thụ thai',
      'menstrual_cycle_phase_ovulation': 'Ngày rụng trứng',
      'menstrual_cycle_phase_normal': 'Giai đoạn bình thường',
      'menstrual_cycle_days': 'ngày',
      'menstrual_cycle_days_left': 'còn {days} ngày',
      'menstrual_cycle_days_ago': '{days} ngày trước',
    },
    'en': {
      // ── Navigation ──
      'home': 'Home',
      'nutrition': 'Nutrition',
      'health': 'Health',
      'profile': 'Profile',

      // ── Profile Page ──
      'settings': 'Settings',
      'personal_info': 'Personal Info',
      'personal_info_sub': 'Update your profile',
      'family_members': 'Family Members',
      'family_members_sub': 'Manage family profiles',
      'account_security': 'Account & Security',
      'account_security_sub': 'Password, authentication',
      'preferences': 'Preferences',
      'notifications': 'Notifications',
      'notifications_sub': 'Manage reminders',
      'dark_mode': 'Dark Mode',
      'dark_mode_on': 'On',
      'dark_mode_off': 'Off',
      'language': 'Language',
      'language_vi': 'Tiếng Việt',
      'language_en': 'English',
      'support': 'Support',
      'help_faq': 'Help & FAQ',
      'about_app': 'About App',
      'version': 'Version',
      'logout': 'Log out',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'user': 'User',
      'choose_language': 'Choose Language',

      // ── Quick Stats ──
      'health_status': 'Health',
      'good': 'Good',
      'meals': 'Meals',
      'today': 'Today',
      'steps': 'Steps',
      'tracking': 'Tracking',
      'hello': 'Hello',
      'health_status_title': 'Health Status',
      'health_metrics_title': 'Health Metrics',
      'unit_mmhg': 'mmHg',
      'unit_percent': '%',
      'today_steps': 'Steps Today',
      'unit_kcal': 'kcal',
      'unit_km': 'km',
      'step_activity_distribution': 'Activity distribution',
      'distance': 'Distance',
      'step_status_sedentary': 'Sedentary',
      'step_status_light': 'Light Activity',
      'step_status_moderate': 'Moderate',
      'step_status_good': 'Good',
      'step_status_very_active': 'Very Active',
      'details': 'Details',

      // ── Photo Options ──
      'choose_from_gallery': 'Choose from gallery',
      'take_photo': 'Take a photo',
      'delete_avatar': 'Delete avatar',
      'uploading_photo': 'Uploading photo...',
      'update_avatar_success': 'Avatar updated successfully!',
      'upload_failed': 'Upload failed. Please try again!',
      'confirm': 'Confirm',
      'confirm_delete_avatar': 'Are you sure you want to delete your avatar?',
      'delete': 'Delete',
      'deleted_avatar': 'Avatar deleted',
      'error': 'Error',

      // ── Today Target ──
      'today_target': 'Today\'s Target',
      'drink_water': 'Water Intake',
      'step_count': 'Steps',
      'meal_calories': 'Meals',
      'step_goal': '10,000 steps',
      'water_goal': '2000 ml',
      'calorie_goal': '2000 kcal',

      // ── Health Page ──
      'health_tracking': 'General health tracking',
      'health_metrics': 'Health Metrics',
      'health_advice': 'Health Advice',

      // ── Nutrition Page ──
      'nutrition_distribution': 'Nutrition Distribution',
      'today_meals': 'Today\'s Meals',
      'no_meals_today': 'No meals yet',
      'no_meals_today_full': 'No meals today',
      'add_meal_hint': 'Add a meal to track nutrition',
      'nutrition_summary': 'Nutrition Summary',
      'add_new_dish': 'Add New Dish',
      'meal_suggestion_ai_title': 'AI Meal Suggestions',
      'meal_suggestion_ai_subtitle': 'Based on your health metrics',
      'meal_suggestion_smart_title': 'Smart Meal Suggestions',
      'meal_suggestion_smart_desc':
          'AI will analyze your health metrics, today\'s nutrition intake,\nand suggest the most suitable meal for you',
      'meal_suggestion_choose_type': 'Choose meal type',
      'meal_suggestion_next_meal': 'Next meal',
      'meal_suggestion_breakfast': 'Breakfast',
      'meal_suggestion_lunch': 'Lunch',
      'meal_suggestion_dinner': 'Dinner',
      'meal_suggestion_snack': 'Snack',
      'meal_suggestion_feature_health_metrics': 'Analyze recent health metrics',
      'meal_suggestion_feature_macro_gaps':
          'Calculate remaining calories/macros for today',
      'meal_suggestion_feature_tdee': 'Calculate TDEE from BMI and steps',
      'meal_suggestion_feature_vietnamese_food':
          'Suggest suitable Vietnamese dishes',
      'meal_suggestion_generate_now': 'Suggest with AI',
      'meal_suggestion_loading_title': 'AI is analyzing your health...',
      'meal_suggestion_loading_desc':
          'Reading recent health metrics and today\'s nutrition',
      'meal_suggestion_error_title': 'Unable to create suggestions',
      'meal_suggestion_daily_summary': 'Today\'s Health Summary',
      'meal_suggestion_nutrition_gaps': 'Nutrients to add',
      'meal_suggestion_suggested_dishes': 'Suggested Dishes',
      'meal_suggestion_regenerate': 'Suggest again',
      'capture_meal_to_analyze': 'Take a food photo to analyze nutrition',
      'food_count': '{count} items',
      'today_calories': 'Today\'s Calories',
      'weekday_mon': 'Mon',
      'weekday_tue': 'Tue',
      'weekday_wed': 'Wed',
      'weekday_thu': 'Thu',
      'weekday_fri': 'Fri',
      'weekday_sat': 'Sat',
      'weekday_sun': 'Sun',

      // ── Meal Capture ──
      'ai_analyzing': 'AI is identifying nutritional content',
      'nutrition_analysis_ai': 'Nutrition Analysis\nby AI',
      'capture_hint':
          'Take or select a photo of your meal, AI will identify\nand analyze detailed nutritional information.',
      'fast_recognition': 'Fast recognition',
      'detailed_calories': 'Detailed calories',
      'food_database': '852+ foods',
      'take_photo_btn': 'Take meal photo',
      'choose_from_gallery_btn': 'Choose from gallery',

      // ── Meal Detail ──
      'food_items': 'Food Items',
      'health_recommendations': 'Health Recommendations',
      'notes': 'Notes',
      'delete_meal': 'Delete Meal',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fat': 'Fat',
      'fiber': 'Fiber',
      'calories': 'Calories',
      'glycemic_index': 'GI Index',

      // ── Meal Analysis ──
      'meal_analysis_result_title': 'Analysis Result',
      'meal_analysis_need_food_item_to_save':
          'Add at least 1 food item to save!',
      'meal_analysis_save_error': 'Save failed: {error}',
      'meal_analysis_saved_success': 'Meal saved successfully!',
      'meal_capture_title': 'Meal analysis',
      'analyzing_meal': 'Analyzing meal...',
      'meal_type_label': 'Meal type',
      'dish_name_label': 'Dish name',
      'dish_name_hint': 'Enter dish name',
      'overview': 'Overview',
      'total_calories': 'Total calories',
      'tap_to_edit': 'Tap to edit',
      'save_meal': 'Save meal',
      'edit_food_item': 'Edit: {name}',
      'portion_grams_label': 'Portion (grams)',
      'nutrition_recalc_note': 'Nutrition values will be recalculated by ratio',
      'invalid_image_title': 'Invalid Image',
      'invalid_image_hint': 'Please take or select a clear photo of your meal so the AI can analyze it accurately.',
      'invalid_image_retake': 'Retake Photo',
      'invalid_image_pick_gallery': 'Choose Another Photo',

      // ── Auth ──
      'forgot_password_title': 'Forgot password',
      'reset_password_title': 'Reset password',
      'reset_password_desc':
          'Enter your email to receive a password reset link. We will send instructions to this email address.',
      'email': 'Email',
      'your_email_hint': 'Your email',
      'please_enter_email': 'Please enter your email',
      'invalid_email_format': 'Invalid email format',
      'send_reset_link': 'Send reset link',
      'back_to_login': 'Back to login',
      'reset_email_sent': 'Password reset email sent. Please check your inbox.',
      'note': 'Note:',
      'reset_password_note_bullets':
          '• Also check spam/junk folder\n• Link is valid for 1 hour\n• If you don\'t receive the email, try again after 5 minutes',

      // ── Auth - Login ──
      'login_title': 'Sign In',
      'login_welcome_back': 'Welcome back!',
      'login_subtitle': 'Manage your health',
      'password': 'Password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'login_btn': 'Sign in',
      'login_with_google': 'Sign in with Google',
      'or': 'Or',
      'no_account': 'Don\'t have an account? ',
      'login_failed': 'Sign in failed',
      // ── Auth - Register ──
      'register': 'Register',
      'register_title': 'Create Account',
      'register_subtitle': 'Register to start managing your health',
      'confirm_password': 'Confirm password',
      'password_requirements': 'Password requirements:',
      'req_valid_email': 'Valid email format (abc@email.com)',
      'req_password_min': 'Password at least 6 characters',
      'req_password_match': 'Passwords match',
      'agree_to': 'I agree to the ',
      'terms_of_use': 'Terms of Use',
      'and': 'and',
      'privacy_policy': 'Privacy Policy',
      'register_btn': 'Register',
      'register_failed': 'Registration failed',
      'have_account': 'Already have an account? ',
      'please_enter_password': 'Please enter password',
      'password_min_6': 'Password must be at least 6 characters',
      'please_enter_confirm_password': 'Please re-enter password',
      'password_not_match': 'Passwords do not match',

      // ── Common ──
      'save': 'Save',
      'edit': 'Edit',
      'reset': 'Reset',
      'search': 'Search',
      'loading': 'Loading...',
      'no_data': 'No data',
      'error_with_message': 'Error: {message}',

      'time': 'Time',
      'status': 'Status',
      'classification': 'Classification',
      'clear_filter': 'Clear filters',
      'record_count': '{count} records',
      'total_records': 'Total records',
      'average': 'Average',
      'steps_per_day': '{count} steps/day',
      'retry': 'Try again',
      'add': 'Add',
      'close': 'Close',
      'not_selected': 'Not selected',
      'not_available': 'N/A',
      'no_results_found': 'No results found',
      'try_change_filters': 'Try changing your filters',
      'no_data_for_filter': 'No data for this filter',
      'no_data_matching_filter': 'No data matching the filter',
      'activity_level': 'Activity level',
      'activity_low': 'Low',
      'activity_moderate': 'Moderate',
      'activity_active': 'Active',
      'bmi_underweight': 'Underweight',
      'bmi_overweight': 'Overweight',
      'bmi_obese': 'Obese',
      'blood_sugar_status': 'Blood sugar status',
      'blood_sugar_low': 'Low blood sugar',
      'blood_sugar_prediabetes_short': 'Pre-DM',
      'blood_sugar_prediabetes': 'Prediabetes',
      'blood_sugar_diabetes': 'Diabetes',
      'measurement_time': 'Measurement time',
      'before_sleep': 'Before sleep',
      'after_wake': 'After waking',
      'sleep_duration': 'Sleep duration',
      'sleep_quality': 'Quality',
      'sleep_duration_severe_shortage': 'Severe shortage',
      'sleep_duration_severe_shortage_full': 'Severe sleep shortage',
      'sleep_duration_shortage': 'Shortage',
      'sleep_duration_ok': 'Okay',
      'sleep_duration_good': 'Good',
      'filter_results': 'Filter results',
      'filter': 'Filter',
      'all': 'All',
      'manual_entry': 'Manual',
      'device': 'Device',
      'status_normal': 'Normal',
      'status_caution': 'Caution',
      'status_no_data': 'No data',
      'health_status_low': 'Low',
      'health_status_high': 'High',
      'health_status_slightly_low': 'Slightly low',
      'health_status_slightly_high': 'Slightly high',
      'status_monitoring': 'Monitoring',
      'status_attention': 'Needs attention',
      'status_danger': 'Danger',
      'apply': 'Apply',
      'date_range_invalid': 'Start date must be before end date',
      'temp_low': 'Low temperature',
      'temp_mild_fever': 'Mild fever',
      'temp_moderate_fever': 'Moderate fever',
      'temp_high_fever': 'High fever',
      'track_temperature': 'Track Temperature',
      'add_temperature_title': 'Add Temperature',
      'edit_temperature_title': 'Update Temperature',
      'confirm_delete_temperature':
          'Are you sure you want to delete this temperature record?',
      'no_temperature_records': 'No temperature data yet',
      'temperature_value': 'Temperature',
      'enter_temperature': 'Enter temperature value',
      'no_step_data': 'No step data',
      'no_sleep_data': 'No sleep data',
      'no_blood_sugar_data': 'No blood sugar data',
      'no_cholesterol_data': 'No cholesterol data',
      'no_blood_pressure_data': 'No blood pressure data',
      'no_hba1c_data': 'No HbA1c data',
      'steps_unit': 'steps',
      'meal_status_fasting': 'Fasting',
      'meal_status_before_meal': 'Before meal',
      'meal_status_after_meal': '2h after meal',
      'meal_status_random': 'Random',

      // ── Notifications ──
      'notifications_title': 'Notifications',
      'unread_count': '{count} unread',
      'mark_all': 'Mark all',
      'deleted_notification': 'Notification deleted',
      'filter_unread': 'Unread',
      'filter_read': 'Read',
      'no_unread_notifications': 'No unread notifications',

      // ── Meal history ──
      'meal_history_title': 'Meal history',
      'ai_analyze': 'AI analyze',
      'no_meals_in_range': 'No meals in this time range',
      'try_another_range': 'Try a different time range',
      'tap_ai_to_start': 'Tap "AI analyze" to get started',
      'week': 'Week',
      'month': 'Month',

      // ── Insert dish (manual meal) ──
      'add_new_meal_title': 'Add new meal',
      'dish_name_section': 'Dish name',
      'dish_name_example_hint': 'e.g., Pho, Rice plate...',
      'search_food_hint': 'Search foods...',
      'meal_notes_hint_optional': 'Meal notes (optional)...',
      'per_100g': 'Per 100g',
      'please_add_at_least_one_food': 'Please add at least 1 food item',
      'default_meal_name': 'Meal',

      // ── Health Goals ──
      'health_goal_title': 'Health Goals',
      'health_goal_daily_activity': 'Daily Activity',
      'health_goal_steps_title': 'Step Count',
      'health_goal_steps_subtitle': 'Daily step target',
      'health_goal_steps_edit_title': 'Step Goal',
      'health_goal_water_title': 'Water Intake',
      'health_goal_water_subtitle': 'Daily water intake target',
      'health_goal_water_edit_title': 'Water Intake Goal',
      'health_goal_calories_title': 'Calorie Intake',
      'health_goal_calories_subtitle': 'Daily calorie target',
      'health_goal_calories_edit_title': 'Calorie Goal',
      'health_goal_sleep_weight': 'Sleep & Weight',
      'health_goal_sleep_title': 'Sleep Duration',
      'health_goal_sleep_subtitle': 'Target sleep hours each night',
      'health_goal_sleep_edit_title': 'Sleep Goal',
      'health_goal_weight_title': 'Target Weight',
      'health_goal_weight_subtitle': 'Your target body weight',
      'health_goal_not_set': 'No goal set',
      'health_goal_reset_defaults': 'Reset to defaults',
      'health_goal_enter_value': 'Enter value ({min} – {max} {unit})',
      'health_goal_invalid_value': 'Invalid value',
      'health_goal_value_range': 'Must be from {min} to {max}',
      'health_goal_reset_title': 'Reset goals',
      'health_goal_reset_confirm':
          'All goals will be reset to default values. Are you sure?',

      // ── Health Overview ──
      'health_overview_title': 'Health Overview',
      'health_overview_measurements': 'Measurements',
      'health_overview_warnings': 'Warnings',
      'health_overview_this_year': 'This year',
      'health_overview_detailed_stats': 'Detailed Stats',
      'health_overview_total_measurements': 'Total measurements',
      'health_overview_daily_average': 'Daily average',
      'health_overview_abnormal_data': 'Abnormal data',
      'health_overview_times_count': '{count} times',
      'health_overview_bp_warning_title': 'Blood Pressure Alert',
      'health_overview_bp_warning_desc':
          'Blood pressure appears high. Limit salty food and do light exercise.',
      'health_overview_bp_stable_title': 'Blood Pressure Stable',
      'health_overview_bp_stable_desc':
          'Keep maintaining a healthy diet and regular exercise.',
      'health_overview_glucose_control_title': 'Control Blood Sugar',
      'health_overview_glucose_control_desc':
          'Blood sugar is high. Consult your doctor and manage your diet.',
      'health_overview_glucose_stable_title': 'Blood Sugar Stable',
      'health_overview_glucose_stable_desc':
          'Keep checking HbA1c periodically for monitoring.',
      'health_overview_fever_title': 'You May Have a Fever',
      'health_overview_fever_desc':
          'Body temperature is high. Drink plenty of water and monitor closely.',
      'health_overview_temperature_normal_title': 'Keep Your Body Warm',
      'health_overview_temperature_normal_desc':
          'Body temperature is normal. Maintain a suitable room temperature.',

      // ── Health Page & Widgets ──
      'tracking_target': 'Tracking Target',
      'today_overview': 'Today\'s Overview',
      'blood_pressure': 'Blood Pressure',
      'hba1c_index': 'HbA1c Index',
      'temperature': 'Temperature',
      'spo2_heart_rate': 'SPO2 & Heart Rate',
      'bmi_weight': 'BMI & Weight',
      'water_intake': 'Water Intake',
      'blood_sugar': 'Blood Sugar',
      'sleep': 'Sleep',
      'cholesterol_label': 'Cholesterol',
      'daily_water': 'Water',
      'heart_rate_label': 'Heart Rate',
      'unit_ml': 'ml',
      'unit_hour': 'hrs',
      'unit_bpm': 'bpm',
      'add_spo2_heart_rate_title': 'Add SPO2 & Heart Rate',
      'edit_spo2_heart_rate_title': 'Update SPO2 & Heart Rate',
      'confirm_delete_spo2_heart_rate':
          'Are you sure you want to delete this record?',
      'no_spo2_heart_rate_records': 'No SPO2 & Heart Rate data yet',
      'spo2_empty_hint': 'Tap + to enter manually or sync from your device',
      'enter_spo2': 'Enter SPO2 (70-100%)',
      'enter_heart_rate': 'Enter heart rate (30-200 bpm)',
      'sync': 'Sync',
      'sync_from_health_connect': 'Sync from Health Connect',
      'health_connect_sync_title': 'Health Connect Sync',
      'health_connect_sync_desc':
          'Get SpO2 & Heart Rate data from your wearable via Health Connect',
      'syncing_health_connect': 'Syncing from Health Connect...',
      'please_wait_moment': 'Please wait a moment',
      'sync_spo2_banner_desc': 'Sync SpO2 & heart rate from your wearable',
      'sync_success_count': 'Synced {count} records from Health Connect',
      'last_7_days': 'Last 7 days',
      'last_30_days': 'Last 30 days',
      'spo2_status_mild': 'Mild oxygen deficiency',
      'spo2_status_moderate': 'Moderate oxygen deficiency',
      'spo2_status_severe': 'Severe oxygen deficiency',
      'heart_rate_slow': 'Slow heart rate',
      'heart_rate_fast_mild': 'Mild fast heart rate',
      'heart_rate_fast_moderate': 'Moderate fast heart rate',
      'heart_rate_fast_high': 'Very fast heart rate',
      'error_occurred': 'An error occurred',
      'tip_today': '💡 Today\'s Tip',
      'tip_water_title': 'Drink enough water',
      'tip_water_desc':
          'Drink at least 2 liters of water daily to maintain health and keep your body functioning well.',
      'tip_walk_title': 'Walk every day',
      'tip_walk_desc':
          'Walking 30 minutes a day reduces cardiovascular risk and improves mood.',
      'tip_sleep_title': 'Get enough sleep',
      'tip_sleep_desc':
          'Sleeping 7-8 hours a night helps the body recover and boosts the immune system.',
      'tip_eat_title': 'Eat healthy',
      'tip_eat_desc':
          'Add greens and fruits to daily meals for essential vitamins.',
      'tip_relax_title': 'Relax your mind',
      'tip_relax_desc':
          'Spend 10 minutes a day meditating or deep breathing to effectively reduce stress.',
      'tip_bp_title': 'Monitor blood pressure',
      'tip_bp_desc':
          'Regularly check blood pressure to detect heart issues early and adjust lifestyle.',
      'tip_exercise_title': 'Exercise',
      'tip_exercise_desc':
          'Exercise at least 150 minutes/week to strengthen cardiovascular and joint health.',
      'weekly_activity': 'Weekly Activity',
      'active_days_recorded': '{days}/7 days with recorded data',
      'no_data_this_week': 'No data this week',
      'this_week': 'This Week',
      'target_reached': 'Target Reached',
      'target': 'Target',
      'day_mon': 'Mon',
      'day_tue': 'Tue',
      'day_wed': 'Wed',
      'day_thu': 'Thu',
      'day_fri': 'Fri',
      'day_sat': 'Sat',
      'day_sun': 'Sun',

      // ── Family Profile ──
      'manage_family_profiles': 'Manage Family Profiles',
      'add_profile': 'Add Profile',
      'no_family_profiles': 'No family profiles yet',
      'family_profile_empty_hint':
          'Add family member profiles to track health for your household',
      'selected': 'Selected',
      'years_old': 'years old',
      'years_old_count': '{count} years old',
      'add_new_profile_title': 'Add New Profile',
      'update_profile_title': 'Update Profile',
      'basic_info': 'Basic Info',
      'health_info': 'Health Info',
      'full_name': 'Full Name',
      'please_enter_full_name': 'Please enter full name',
      'relationship_label': 'Relationship *',
      'gender': 'Gender',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'gender_other': 'Other',
      'blood_type': 'Blood Type',
      'height_cm': 'Height (cm)',
      'weight_kg': 'Weight (kg)',
      'height_invalid': 'Invalid height',
      'weight_invalid': 'Invalid weight',
      'enter_name_preview': 'Enter name to preview',
      'confirm_delete_profile': 'Are you sure you want to delete this profile?',
      'rel_self': 'Self',
      'rel_spouse': 'Spouse',
      'rel_child': 'Child',
      'rel_parent': 'Parent',
      'rel_sibling': 'Sibling',
      'rel_grandparent': 'Grandparent',
      'rel_other': 'Other',
      'update_btn': 'Update',

      // ── Edit Profile ──
      'edit_profile_title': 'Edit Profile',
      'phone_number': 'Phone Number',
      'date_of_birth_label': 'Date of Birth',
      'choose_date_of_birth': 'Choose date of birth',
      'address': 'Address',
      'emergency_contact': 'Emergency Contact',
      'emergency_contact_name': 'Contact Name',
      'emergency_phone': 'Emergency Phone',
      'update_success': '✅ Update successful!',
      'not_updated': 'Not updated',

      // ── Blood Sugar / Insert ──
      'track_blood_sugar': 'Track Blood Sugar',
      'add_blood_sugar_title': 'Add Blood Sugar',
      'edit_blood_sugar_title': 'Edit Blood Sugar',
      'confirm_delete_blood_sugar':
          'Are you sure you want to delete this blood sugar record?',
      'no_blood_sugar_records': 'No blood sugar data yet',
      'add_new_record_hint': 'Tap + to add a new record',
      'select_time': 'Select time',
      'blood_sugar_value': 'Blood Sugar (mg/dL)',
      'enter_blood_sugar': 'Enter blood sugar value',
      'note_optional': 'Note (optional)',
      'note_hint': 'Enter note...',

      // ── Blood Pressure ──
      'track_blood_pressure': 'Track Blood Pressure',
      'add_blood_pressure_title': 'Add Blood Pressure',
      'edit_blood_pressure_title': 'Edit Blood Pressure',
      'confirm_delete_blood_pressure':
          'Are you sure you want to delete this blood pressure record?',
      'blood_pressure_chart_title': 'Blood Pressure Chart',
      'blood_pressure_systolic': 'Systolic',
      'blood_pressure_diastolic': 'Diastolic',
      'enter_blood_pressure_systolic': 'Enter systolic value',
      'enter_blood_pressure_diastolic': 'Enter diastolic value',
      'blood_pressure_systolic_greater_error':
          'Systolic value must be greater than diastolic value',
      'blood_pressure_diastolic_less_error':
          'Diastolic value must be less than systolic value',
      'blood_pressure_low': 'Low blood pressure',
      'blood_pressure_elevated': 'Elevated',
      'blood_pressure_stage_1': 'Hypertension stage 1',
      'blood_pressure_stage_2': 'Hypertension stage 2',
      'blood_pressure_stage_3': 'Hypertension stage 3',
      'please_select_date_range': 'Please select a date range',

      // ── HbA1c ──
      'track_hba1c': 'Track HbA1c',
      'hba1c_chart_title': 'HbA1c Chart',
      'add_hba1c_title': 'Add HbA1c',
      'edit_hba1c_title': 'Update HbA1c',
      'confirm_delete_hba1c':
          'Are you sure you want to delete this HbA1c record?',
      'no_hba1c_records': 'No HbA1c data yet',
      'enter_hba1c': 'Enter HbA1c value',
      'hba1c_status_normal': 'Normal',
      'hba1c_status_prediabetes': 'Prediabetes',
      'hba1c_status_diabetes': 'Diabetes',
      'hba1c_status_high': 'High',
      'hba1c_info_prefix': 'The ',
      'hba1c_info_average': ' reflects average blood sugar over the last ',
      'hba1c_info_period': '2-3 months. ',
      'hba1c_info_target':
          'The recommended treatment target for people with diabetes is',
      'hba1c_target_value': 'HbA1c < 7%',

      // ── Medical Notes (Admin) ──
      'medical_notes_title': 'Medical Notes',
      'selected_patient': 'Selected Patient',
      'select_patient': 'Select Patient',
      'tap_to_select_patient': 'Tap to select a patient',
      'choose_patient_title': 'Choose Patient',
      'search_patient_hint': 'Search patients...',
      'patient_not_found': 'No patients found',
      'try_other_keyword': 'Try a different keyword',
      'start_notes': 'Start Notes',
      'tap_patient_bar': 'Tap the patient selector above',
      'to_view_or_add': 'to view or add medical notes',
      'note_list': 'Note List',
      'add_note': 'Add Note',
      'not_yet_updated': 'Not updated',

      // English (en.json) - cần thêm
      "no_read_notifications": "No read notifications",
      "no_notifications": "No notifications yet",
      "just_now": "Just now",
      "minutes_ago": "{count} minutes ago",
      "hours_ago": "{count} hours ago",
      "days_ago": "{count} days ago",

      // ── Menstrual Cycle ──
      'menstrual_cycle': 'Menstrual Cycle',
      'menstrual_cycle_subtitle': 'days/cycle',
      'menstrual_cycle_overview': 'Overview',
      'menstrual_cycle_calendar': 'Calendar',
      'menstrual_cycle_history': 'History',
      'menstrual_cycle_add': 'Add Cycle',
      'menstrual_cycle_edit': 'Edit Cycle',
      'menstrual_cycle_new': 'Add New Cycle',
      'menstrual_cycle_start_date': 'Period Start Date',
      'menstrual_cycle_end_date': 'Period End Date (optional)',
      'menstrual_cycle_period_length': 'Period Length',
      'menstrual_cycle_symptoms': 'Symptoms',
      'menstrual_cycle_note': 'Note (optional)',
      'menstrual_cycle_save': 'Save Cycle',
      'menstrual_cycle_update': 'Update',
      'menstrual_cycle_delete_confirm':
          'Are you sure you want to delete this cycle?',
      'menstrual_cycle_no_data': 'No cycle data yet',
      'menstrual_cycle_next': 'Next Period',
      'menstrual_cycle_ovulation': 'Ovulation',
      'menstrual_cycle_fertile_window': 'Fertile Window',
      'menstrual_cycle_ongoing': 'Ongoing',
      'menstrual_cycle_latest': 'Latest Cycle',
      'menstrual_cycle_avg_length': 'Avg Cycle',
      'menstrual_cycle_total': 'Total Cycles',
      'menstrual_cycle_phase_period': 'Menstruating',
      'menstrual_cycle_phase_fertile': 'Fertile Window',
      'menstrual_cycle_phase_ovulation': 'Ovulation Day',
      'menstrual_cycle_phase_normal': 'Normal Phase',
      'menstrual_cycle_days': 'days',
      'menstrual_cycle_days_left': '{days} days left',
      'menstrual_cycle_days_ago': '{days} days ago',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final normalizedCode = languageCode;
    final raw =
        _localizedValues[normalizedCode]?[key] ??
        _localizedValues['vi']?[key] ??
        key;

    if (params == null || params.isEmpty) return raw;

    var out = raw;
    for (final entry in params.entries) {
      out = out.replaceAll('{${entry.key}}', entry.value);
    }
    return out;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLanguageCodes
      .contains(locale.languageCode.toLowerCase());

  @override
  Future<AppLocalizations> load(Locale locale) {
    // No async work needed; keep localization load synchronous.
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// Extension for easy access
extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key, {Map<String, String>? params}) =>
      AppLocalizations.of(this).translate(key, params: params);
}
